import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const tmp=fs.mkdtempSync(path.join(os.tmpdir(),"rath-whoop-test-"));process.env.RATHWORKSPACE_DB=path.join(tmp,"whoop.db");process.env.WHOOP_CLIENT_ID="fixture-client";process.env.WHOOP_CLIENT_SECRET="fixture-client-secret";process.env.NEXTAUTH_SECRET="fixture-nextauth-secret";
let loaded:Promise<any>|null=null;function setup(){if(!loaded)loaded=Promise.all([import("@/lib/health"),import("@/lib/sources/whoop"),import("@/db")]).then(([health,whoop,db])=>({health,whoop,db}));return loaded}
test.after(async()=>{const {db}=await setup();try{db.getDb().close()}catch{}fs.rmSync(tmp,{recursive:true,force:true});delete process.env.WHOOP_CLIENT_ID;delete process.env.WHOOP_CLIENT_SECRET;delete process.env.NEXTAUTH_SECRET});
function json(data:any,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json"}})}
function setEnabled(db:any,enabled:boolean){db.getDb().prepare(`INSERT INTO connections(service,surface,enabled,health,state,detail) VALUES ('whoop','dashboard',?,'unknown',?,'fixture') ON CONFLICT(service,surface) DO UPDATE SET enabled=excluded.enabled`).run(enabled?1:0,enabled?"on_broken":"off")}

test("snapshot distinguishes stale and broken authorization from enabled-row existence",async()=>{const {health,db}=await setup();setEnabled(db,true);db.getDb().prepare(`INSERT INTO whoop_tokens (user_id,email,refresh_token_enc,enabled,last_sync,last_error,connected_at) VALUES (1,'test@example.com','encrypted-fixture',1,?,?,'2026-08-01T00:00:00Z')`).run("2026-08-01T00:00:00Z",null);let snap=health.healthSnapshot("2026-08-14T12:00:00Z");assert.equal(snap.connections.whoop.status,"stale");assert.equal(snap.readiness.available,false);db.getDb().prepare("UPDATE whoop_tokens SET last_error='refresh failed fixture' WHERE user_id=1").run();snap=health.healthSnapshot("2026-08-14T12:00:00Z");assert.equal(snap.connections.whoop.status,"broken");assert.equal(snap.dataQuality.status,"broken")});

test("metric timestamps remain independent so fresh strain cannot make old recovery current",async()=>{const {health,db}=await setup();setEnabled(db,true);db.getDb().prepare("UPDATE whoop_tokens SET last_sync=?,last_error=NULL WHERE user_id=1").run("2026-08-14T11:00:00Z");db.getDb().prepare(`INSERT INTO whoop_daily (day,recovery,hrv_ms,rhr_bpm,sleep_hours,sleep_performance,strain,ts,recovery_updated_at,sleep_updated_at,strain_updated_at) VALUES ('2026-08-10',61,52,58,7.4,83,NULL,'2026-08-10T12:00:00Z','2026-08-10T11:00:00Z','2026-08-10T10:00:00Z',NULL)`).run();db.getDb().prepare(`INSERT INTO whoop_daily (day,recovery,hrv_ms,rhr_bpm,sleep_hours,sleep_performance,strain,ts,recovery_updated_at,sleep_updated_at,strain_updated_at) VALUES ('2026-08-14',NULL,NULL,NULL,NULL,NULL,12.3,'2026-08-14T11:30:00Z',NULL,NULL,'2026-08-14T11:30:00Z')`).run();const snap=health.healthSnapshot("2026-08-14T12:00:00Z");assert.equal(snap.whoop.recovery.value,61);assert.equal(snap.whoop.recovery.freshness,"stale");assert.equal(snap.whoop.strain.value,12.3);assert.equal(snap.whoop.strain.freshness,"fresh");assert.equal(snap.readiness.available,false)});

test("OAuth account replacement is atomic, erases the old credential, quarantines old data, and isolates caches",async()=>{const {whoop,db}=await setup();setEnabled(db,true);const seenAuth:string[]=[];const request=async(input:RequestInfo|URL,init?:RequestInit)=>{const url=String(input);if(url.endsWith("/oauth/oauth2/token")){const body=String(init?.body||"");const code=new URLSearchParams(body).get("code");return json({access_token:code==="code-one"?"access-one":"access-two",refresh_token:code==="code-one"?"refresh-one":"refresh-two",expires_in:3600,scope:"offline"})}if(url.endsWith("/user/profile/basic")){const auth=(init?.headers as any)?.authorization||"";seenAuth.push(auth);return json(auth.includes("access-two")?{user_id:2,email:"two@example.com",first_name:"Two"}:{user_id:1,email:"one@example.com",first_name:"One"})}return json({},404)};
  await whoop.handleCallback("code-one",{request,timeoutMs:100});db.getDb().prepare("INSERT INTO health_workouts(idempotency_key,source,external_id,title,started_at) VALUES ('fixture-old-account-workout','whoop','old-account-workout','Old','2026-08-10T12:00:00Z')").run();db.getDb().prepare("INSERT OR REPLACE INTO whoop_daily(day,recovery,ts) VALUES ('2026-08-10',70,'2026-08-10T12:00:00Z')").run();
  await whoop.handleCallback("code-two",{request,timeoutMs:100});const rows=db.getDb().prepare("SELECT user_id,enabled,refresh_token_enc FROM whoop_tokens ORDER BY user_id").all();assert.equal((rows[0] as any).user_id,1);assert.equal((rows[0] as any).enabled,0);assert.equal((rows[0] as any).refresh_token_enc,null);assert.equal((rows[1] as any).user_id,2);assert.equal((rows[1] as any).enabled,1);assert.ok((rows[1] as any).refresh_token_enc);assert.ok((db.getDb().prepare("SELECT deleted_at FROM health_workouts WHERE external_id='old-account-workout'").get() as any).deleted_at);assert.equal((db.getDb().prepare("SELECT COUNT(*) n FROM whoop_daily").get() as any).n,0);const archive=db.getDb().prepare("SELECT account_identity,reason,day,payload_json FROM health_whoop_daily_archive WHERE day='2026-08-10' ORDER BY id DESC LIMIT 1").get() as any;assert.equal(archive.reason,"account_replaced");assert.equal(archive.day,"2026-08-10");assert.equal(JSON.parse(archive.payload_json).recovery,70);assert.ok(archive.account_identity);const source=db.getDb().prepare("SELECT account_identity,generation,cursor FROM health_sync_state WHERE source='whoop'").get() as any;assert.ok(source.account_identity);assert.notEqual(source.account_identity,"2");assert.equal(source.cursor,null);
  seenAuth.length=0;const health=await whoop.healthCheck({request,timeoutMs:100});assert.equal(health.ok,true);assert.deepEqual(seenAuth,["Bearer access-two"]);
});

test("partial endpoint failures preserve useful ingestion but expose only a fixed diagnostic code",async()=>{const {whoop,db}=await setup();setEnabled(db,true);db.getDb().prepare("UPDATE whoop_tokens SET last_sync=?,last_error=NULL WHERE user_id=2").run("2026-08-14T10:00:00Z");const request=async(input:RequestInfo|URL)=>{const url=String(input);if(url.includes("/cycle"))return json({records:[{id:7,start:"2026-08-14T04:00:00Z",updated_at:"2026-08-14T11:00:00Z",score:{strain:10}}]});if(url.includes("/recovery")||url.includes("/activity/sleep"))return json({records:[]});if(url.includes("/activity/workout"))return json({error:"fixture"},503);if(url.includes("/measurement/body"))return json({error:"fixture"},500);return json({},404)};const result=await whoop.pollWhoop({request,timeoutMs:100});assert.deepEqual(result,{status:"degraded",detail:"WHOOP data sync completed only partially"});const token=db.getDb().prepare("SELECT last_sync,last_error FROM whoop_tokens WHERE user_id=2").get() as any;assert.equal(token.last_sync,"2026-08-14T10:00:00Z");assert.equal(token.last_error,"WHOOP_DATA_PARTIAL_SYNC");assert.equal((db.getDb().prepare("SELECT strain FROM whoop_daily WHERE day='2026-08-14'").get() as any).strain,10)});

test("recovery waits for its cycle anchor instead of leaving a fallback trend day",async()=>{const {whoop,db}=await setup();setEnabled(db,true);let cycleAvailable=false;const request=async(input:RequestInfo|URL)=>{const url=String(input);if(url.includes("/cycle"))return cycleAvailable?json({records:[{id:777,start:"2026-08-14T23:30:00Z",updated_at:"2026-08-15T12:00:00Z",score:{}}]}):json({error:"fixture"},503);if(url.includes("/recovery"))return json({records:[{cycle_id:777,created_at:"2026-08-15T08:00:00Z",updated_at:"2026-08-15T12:00:00Z",score:{recovery_score:81}}]});if(url.includes("/activity/sleep"))return json({records:[]});if(url.includes("/activity/workout"))return json({records:[{id:"anchor-proof-workout",start:"2026-08-15T09:00:00Z",end:"2026-08-15T10:00:00Z",updated_at:"2026-08-15T10:30:00Z",sport_name:"Other",score:{strain:6}}]});if(url.includes("/measurement/body"))return json({});return json({},404)};
  const first=await whoop.pollWhoop({request,timeoutMs:100,now:()=>"2026-08-15T13:00:00.000Z"});assert.deepEqual(first,{status:"degraded",detail:"WHOOP data sync completed only partially"});assert.equal((db.getDb().prepare("SELECT COUNT(*) n FROM whoop_daily WHERE recovery=81").get() as any).n,0);assert.equal((db.getDb().prepare("SELECT COUNT(*) n FROM health_workouts WHERE source='whoop' AND source_external_id='anchor-proof-workout' AND deleted_at IS NULL").get() as any).n,1);assert.equal((db.getDb().prepare("SELECT last_error FROM whoop_tokens WHERE user_id=2").get() as any).last_error,"WHOOP_DATA_PARTIAL_SYNC");
  cycleAvailable=true;const second=await whoop.pollWhoop({request,timeoutMs:100,now:()=>"2026-08-15T14:00:00.000Z"});assert.deepEqual(second,{status:"healthy",detail:"WHOOP sync complete"});assert.deepEqual(db.getDb().prepare("SELECT day,recovery FROM whoop_daily WHERE day IN ('2026-08-14','2026-08-15') AND recovery IS NOT NULL ORDER BY day").all(),[{day:"2026-08-14",recovery:81}]);assert.equal((db.getDb().prepare("SELECT last_error FROM whoop_tokens WHERE user_id=2").get() as any).last_error,null);
});

test("invalid cycle starts cannot create daily or recovery rows while valid offset anchors and safe records still ingest",async()=>{const {whoop,db}=await setup();setEnabled(db,true);const request=async(input:RequestInfo|URL)=>{const url=String(input);if(url.includes("/cycle"))return json({records:[{id:1001,start:"not-a-date",score:{strain:11}},{id:1002,start:"2031-02-31T04:00:00Z",score:{strain:12}},{id:1003,start:"2031-03-02T04:00:00",score:{strain:13}},{id:1004,start:"2031-03-03T23:30:00-04:00",score:{strain:14}}]});if(url.includes("/recovery"))return json({records:[{cycle_id:1001,created_at:"2031-03-04T10:00:00Z",score:{recovery_score:31}},{cycle_id:1002,created_at:"2031-03-04T10:00:00Z",score:{recovery_score:32}},{cycle_id:1003,created_at:"2031-03-04T10:00:00Z",score:{recovery_score:33}},{cycle_id:1004,created_at:"2031-03-04T10:00:00Z",score:{recovery_score:84}}]});if(url.includes("/activity/sleep"))return json({records:[]});if(url.includes("/activity/workout"))return json({records:[{id:"invalid-anchor-safe-workout",start:"2031-03-04T12:00:00Z",end:"2031-03-04T13:00:00Z",sport_name:"Other",score:{strain:5}}]});if(url.includes("/measurement/body"))return json({});return json({},404)};
  const result=await whoop.pollWhoop({request,timeoutMs:100,now:()=>"2031-03-04T14:00:00.000Z"});assert.equal(result.status,"healthy");assert.equal((db.getDb().prepare("SELECT COUNT(*) n FROM whoop_daily WHERE recovery IN (31,32,33)").get() as any).n,0);assert.equal((db.getDb().prepare("SELECT COUNT(*) n FROM whoop_daily WHERE day IN ('not-a-date','2031-02-31','2031-03-02')").get() as any).n,0);assert.deepEqual(db.getDb().prepare("SELECT day,recovery,strain FROM whoop_daily WHERE recovery=84").get(),{day:"2031-03-03",recovery:84,strain:14});assert.equal((db.getDb().prepare("SELECT COUNT(*) n FROM health_workouts WHERE source='whoop' AND source_external_id='invalid-anchor-safe-workout' AND deleted_at IS NULL").get() as any).n,1);
});

test("WHOOP network failures are bounded and exposed as sanitized fixed codes",async()=>{const {whoop,db}=await setup();setEnabled(db,true);const hanging=async(_input:RequestInfo|URL,init?:RequestInit)=>new Promise<Response>((_resolve,reject)=>init?.signal?.addEventListener("abort",()=>reject(Object.assign(new Error("provider-secret-body"),{name:"AbortError"}))));const started=Date.now();const result=await whoop.healthCheck({request:hanging,timeoutMs:10});assert.equal(result.ok,false);assert.equal(result.detail,"WHOOP_AUTH_PROFILE_CHECK_FAILED");assert.ok(Date.now()-started<500);await assert.rejects(()=>whoop.handleCallback("bad",{request:async(input:RequestInfo|URL)=>String(input).endsWith("/oauth/oauth2/token")?json({error_description:"provider-secret-body"},401):json({},404),timeoutMs:100}),(error:any)=>{assert.equal(error.message,"WHOOP_TOKEN_REJECTED");assert.doesNotMatch(error.message,/provider-secret-body/);return true})});

test("successful auth checks do not clear a prior data-sync error",async()=>{const {whoop,db}=await setup();setEnabled(db,true);db.getDb().prepare("UPDATE whoop_tokens SET last_error='fixture data sync error',auth_error='old auth error' WHERE user_id=2").run();const result=await whoop.healthCheck({request:async(input:RequestInfo|URL,init?:RequestInit)=>String(input).endsWith("/user/profile/basic")?json({user_id:2,email:"two@example.com",first_name:"Two"}):json({},404),timeoutMs:100});assert.equal(result.ok,true);assert.deepEqual(db.getDb().prepare("SELECT last_error,auth_error FROM whoop_tokens WHERE user_id=2").get(),{last_error:"fixture data sync error",auth_error:null})});

test("WHOOP profile body values never project their synthetic internal timestamp as measured time",async()=>{const {health,whoop,db}=await setup();setEnabled(db,true);const request=async(input:RequestInfo|URL)=>{const url=String(input);if(url.includes("/cycle")||url.includes("/recovery")||url.includes("/activity/sleep")||url.includes("/activity/workout"))return json({records:[]});if(url.includes("/measurement/body"))return json({height_meter:1.8,weight_kilogram:88});return json({},404)};let result=await whoop.pollWhoop({request,timeoutMs:100});assert.equal(result.status,"healthy");const first=db.getDb().prepare("SELECT measured_at,observation_at_known FROM health_body_measurements WHERE source='whoop' AND source_external_id='current' AND deleted_at IS NULL").get() as any;assert.equal(first.observation_at_known,0);await new Promise(resolve=>setTimeout(resolve,5));result=await whoop.pollWhoop({request,timeoutMs:100});assert.equal(result.status,"healthy");const second=db.getDb().prepare("SELECT measured_at,observation_at_known FROM health_body_measurements WHERE source='whoop' AND source_external_id='current' AND deleted_at IS NULL").get() as any;assert.equal(second.measured_at,first.measured_at);const snap=health.healthSnapshot();const projected=snap.body.history.find((row:any)=>row.source==="whoop");assert.equal(snap.body.latestFreshness,"unknown");assert.equal(snap.body.latestAgeHours,null);assert.equal(snap.body.latest.measuredAt,null);assert.equal(projected.measuredAt,null);assert.equal(projected.externalId,"current");assert.equal(snap.body.trendBasis,null);assert.equal(JSON.stringify(snap).includes(first.measured_at),false)});

test("WHOOP body and workout IDs stay account-scoped across switches and restore only the returning account",async()=>{
  const {health,whoop,db}=await setup();setEnabled(db,true);let activeUser=401,weight=81,title="Account A activity";
  const request=async(input:RequestInfo|URL,_init?:RequestInit)=>{const url=String(input);if(url.endsWith("/oauth/oauth2/token"))return json({access_token:`access-${activeUser}`,refresh_token:`refresh-${activeUser}`,expires_in:3600,scope:"offline"});if(url.endsWith("/user/profile/basic"))return json({user_id:activeUser,email:`${activeUser}@example.com`,first_name:`User ${activeUser}`});if(url.includes("/cycle")||url.includes("/recovery")||url.includes("/activity/sleep"))return json({records:[]});if(url.includes("/activity/workout"))return json({records:[{id:"shared-whoop-workout",start:"2026-08-23T08:00:00Z",end:"2026-08-23T09:00:00Z",updated_at:"2026-08-23T09:30:00Z",sport_name:title,score:{strain:activeUser===401?8:13,kilojoule:activeUser===401?500:700}}]});if(url.includes("/measurement/body"))return json({weight_kilogram:weight});return json({},404)};
  await whoop.handleCallback("account-401",{request,timeoutMs:100});assert.equal((await whoop.pollWhoop({request,timeoutMs:100,now:()=>"2026-08-23T10:00:00.000Z"})).status,"healthy");
  activeUser=402;weight=93;title="Account B activity";await whoop.handleCallback("account-402",{request,timeoutMs:100});assert.equal((await whoop.pollWhoop({request,timeoutMs:100,now:()=>"2026-08-23T11:00:00.000Z"})).status,"healthy");
  let bodies=db.getDb().prepare("SELECT external_id,source_account_identity,source_external_id,weight_kg,deleted_at FROM health_body_measurements WHERE source='whoop' AND source_external_id='current' AND weight_kg IN (81,93) ORDER BY weight_kg").all() as any[];
  let workouts=db.getDb().prepare("SELECT external_id,source_account_identity,source_external_id,title,deleted_at FROM health_workouts WHERE source='whoop' AND source_external_id='shared-whoop-workout' ORDER BY title").all() as any[];
  assert.equal(bodies.length,2);assert.equal(new Set(bodies.map(row=>row.external_id)).size,2);assert.equal(new Set(bodies.map(row=>row.source_account_identity)).size,2);assert.ok(bodies.find(row=>row.weight_kg===81)?.deleted_at);assert.equal(bodies.find(row=>row.weight_kg===93)?.deleted_at,null);
  assert.equal(workouts.length,2);assert.equal(new Set(workouts.map(row=>row.external_id)).size,2);assert.equal(new Set(workouts.map(row=>row.source_account_identity)).size,2);assert.equal(workouts.every(row=>row.source_external_id==="shared-whoop-workout"),true);assert.ok(workouts.find(row=>row.title==="Account A activity")?.deleted_at);assert.equal(workouts.find(row=>row.title==="Account B activity")?.deleted_at,null);
  let snapshot=health.dashboardHealthSnapshot("2026-08-23T11:05:00.000Z");assert.equal(snapshot.body.latest.externalId,"current");assert.equal(snapshot.body.latest.weightKg,93);assert.equal(snapshot.body.history.some((row:any)=>row.weightKg===81),false);assert.equal(snapshot.training.activities.some((row:any)=>row.externalId==="shared-whoop-workout"&&row.title==="Account B activity"),true);assert.equal(snapshot.training.activities.some((row:any)=>row.title==="Account A activity"),false);
  activeUser=401;weight=82;title="Account A restored";await whoop.handleCallback("restore-account-401",{request,timeoutMs:100});assert.equal((await whoop.pollWhoop({request,timeoutMs:100,now:()=>"2026-08-23T12:00:00.000Z"})).status,"healthy");
  bodies=db.getDb().prepare("SELECT source_account_identity,weight_kg,deleted_at FROM health_body_measurements WHERE source='whoop' AND source_external_id='current' AND weight_kg IN (82,93) ORDER BY weight_kg").all() as any[];workouts=db.getDb().prepare("SELECT source_account_identity,title,deleted_at FROM health_workouts WHERE source='whoop' AND source_external_id='shared-whoop-workout' ORDER BY title").all() as any[];
  assert.equal(bodies.filter(row=>row.deleted_at==null).length,1);assert.equal(bodies.find(row=>row.weight_kg===82)?.deleted_at,null);assert.ok(bodies.find(row=>row.weight_kg===93)?.deleted_at);assert.equal(workouts.filter(row=>row.deleted_at==null).length,1);assert.equal(workouts.find(row=>row.title==="Account A restored")?.deleted_at,null);assert.ok(workouts.find(row=>row.title==="Account B activity")?.deleted_at);
  snapshot=health.dashboardHealthSnapshot("2026-08-23T12:05:00.000Z");assert.equal(snapshot.body.latest.weightKg,82);assert.equal(snapshot.body.history.some((row:any)=>row.weightKg===93),false);assert.equal(snapshot.training.activities.some((row:any)=>row.externalId==="shared-whoop-workout"&&row.title==="Account A restored"),true);assert.equal(snapshot.training.activities.some((row:any)=>row.title==="Account B activity"),false);
  activeUser=2;await whoop.handleCallback("restore-account-2",{request,timeoutMs:100});
});

test("WHOOP metric commits are monotonic per upstream timestamp even when a later poll returns stale data",async()=>{const {whoop,db}=await setup();setEnabled(db,true);const poll=(now:string,recovery:number,updatedAt:string)=>whoop.pollWhoop({timeoutMs:100,now:()=>now,request:async(input:RequestInfo|URL)=>{const url=String(input);if(url.includes("/cycle"))return json({records:[{id:820,start:"2026-08-20T04:00:00Z",updated_at:updatedAt,score:{}}]});if(url.includes("/recovery"))return json({records:[{cycle_id:820,created_at:updatedAt,updated_at:updatedAt,score:{recovery_score:recovery,hrv_rmssd_milli:55,resting_heart_rate:57}}]});if(url.includes("/activity/sleep")||url.includes("/activity/workout"))return json({records:[]});if(url.includes("/measurement/body"))return json({});return json({},404)}});
  assert.equal((await poll("2026-08-20T14:00:00.000Z",91,"2026-08-20T13:00:00Z")).status,"healthy");assert.equal((await poll("2026-08-20T15:00:00.000Z",22,"2026-08-20T12:00:00Z")).status,"healthy");
  assert.deepEqual(db.getDb().prepare("SELECT recovery,hrv_ms,rhr_bpm,recovery_updated_at FROM whoop_daily WHERE day='2026-08-20'").get(),{recovery:91,hrv_ms:55,rhr_bpm:57,recovery_updated_at:"2026-08-20T13:00:00.000Z"});
});

test("same-account WHOOP lease skips concurrent requests and expiry recovery keeps newer metrics",async()=>{const {whoop,db}=await setup();setEnabled(db,true);let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);let reached!:()=>void;const atGate=new Promise<void>(resolve=>reached=resolve);
  const oldPoll=whoop.pollWhoop({timeoutMs:1000,now:()=>"2026-08-21T12:00:00.000Z",request:async(input:RequestInfo|URL)=>{const url=String(input);if(url.includes("/cycle")){reached();await gate;return json({records:[{id:821,start:"2026-08-21T04:00:00Z",updated_at:"2026-08-21T11:00:00Z",score:{}}]})}if(url.includes("/recovery"))return json({records:[{cycle_id:821,created_at:"2026-08-21T11:00:00Z",updated_at:"2026-08-21T11:00:00Z",score:{recovery_score:30}}]});if(url.includes("/activity/sleep")||url.includes("/activity/workout"))return json({records:[]});if(url.includes("/measurement/body"))return json({});return json({},404)}});await atGate;
  let blockedCalls=0;const blocked=await whoop.pollWhoop({now:()=>"2026-08-21T12:00:01.000Z",request:async()=>{blockedCalls++;return json({})}});assert.deepEqual(blocked,{status:"degraded",detail:"WHOOP sync already in progress"});assert.equal(blockedCalls,0);
  db.getDb().prepare("UPDATE health_sync_state SET lease_expires_at=? WHERE source='whoop'").run("2026-08-21T12:30:00.000Z");
  const newer=await whoop.pollWhoop({timeoutMs:100,now:()=>"2026-08-21T13:00:00.000Z",request:async(input:RequestInfo|URL)=>{const url=String(input);if(url.includes("/cycle"))return json({records:[{id:821,start:"2026-08-21T04:00:00Z",updated_at:"2026-08-21T12:45:00Z",score:{}}]});if(url.includes("/recovery"))return json({records:[{cycle_id:821,created_at:"2026-08-21T12:45:00Z",updated_at:"2026-08-21T12:45:00Z",score:{recovery_score:88}}]});if(url.includes("/activity/sleep")||url.includes("/activity/workout"))return json({records:[]});if(url.includes("/measurement/body"))return json({});return json({},404)}});assert.equal(newer.status,"healthy");
  release();const older=await oldPoll;assert.equal(older.status,"degraded");assert.match(older.detail,/changed during sync/i);assert.deepEqual(db.getDb().prepare("SELECT recovery,recovery_updated_at FROM whoop_daily WHERE day='2026-08-21'").get(),{recovery:88,recovery_updated_at:"2026-08-21T12:45:00.000Z"});assert.deepEqual(db.getDb().prepare("SELECT lease_token,lease_expires_at FROM health_sync_state WHERE source='whoop'").get(),{lease_token:null,lease_expires_at:null});
});

test("public and private snapshots sanitize raw WHOOP OAuth and API bodies at the read boundary",async()=>{const {health,db}=await setup();setEnabled(db,true);db.getDb().prepare("UPDATE whoop_tokens SET enabled=0").run();db.getDb().prepare(`INSERT OR REPLACE INTO whoop_tokens(user_id,email,refresh_token_enc,enabled,last_sync,last_error,auth_error,connected_at) VALUES (77,'safe@example.com','fixture',1,'2026-08-15T00:00:00Z',?,?,'2026-08-15T00:00:00Z')`).run("RAW_API_BODY provider-secret-fragment","RAW_OAUTH_BODY error_description provider-secret-fragment");for(const snapshot of [health.healthSnapshot("2026-08-15T01:00:00Z"),health.privateHealthSnapshot("2026-08-15T01:00:00Z")]){const serialized=JSON.stringify(snapshot);assert.doesNotMatch(serialized,/RAW_API_BODY|RAW_OAUTH_BODY|provider-secret-fragment|error_description/);assert.equal(snapshot.connections.whoop.authError,"WHOOP_AUTH_FAILED");assert.equal(snapshot.connections.whoop.dataSyncError,"WHOOP_DATA_SYNC_FAILED");assert.equal(snapshot.connections.whoop.lastError,"WHOOP_AUTH_FAILED");assert.equal(snapshot.connections.whoop.detail,"WHOOP authorization needs attention; reconnect from Connections")}db.getDb().prepare("DELETE FROM whoop_tokens WHERE user_id=77").run();db.getDb().prepare("UPDATE whoop_tokens SET enabled=1 WHERE user_id=2").run()});

test("disable or account replacement during an in-flight WHOOP poll discards all staged writes",async()=>{const {whoop,db}=await setup();setEnabled(db,true);db.getDb().prepare("UPDATE whoop_tokens SET last_error=NULL,auth_error=NULL WHERE user_id=2").run();let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);let reached!:()=>void;const atGate=new Promise<void>(resolve=>reached=resolve);const request=async(input:RequestInfo|URL)=>{const url=String(input);if(url.includes("/cycle")){reached();await gate;return json({records:[{id:900,start:"2026-08-14T04:00:00Z",score:{strain:14}}]})}if(url.includes("/recovery")||url.includes("/activity/sleep")||url.includes("/activity/workout"))return json({records:[]});if(url.includes("/measurement/body"))return json({});return json({},404)};const polling=whoop.pollWhoop({request,timeoutMs:1000});await atGate;const {setEnabled:setConnectionEnabled}=await import("@/lib/connections");setConnectionEnabled("whoop","dashboard",false);release();const result=await polling;assert.equal(result.status,"degraded");assert.match(result.detail,/changed during sync/i);assert.equal((db.getDb().prepare("SELECT COUNT(*) n FROM whoop_daily WHERE day='2026-08-14' AND strain=14").get() as any).n,0);
  setEnabled(db,true);let releaseOld!:()=>void;const oldGate=new Promise<void>(resolve=>releaseOld=resolve);let reachedOld!:()=>void;const atOldGate=new Promise<void>(resolve=>reachedOld=resolve);const oldPoll=whoop.pollWhoop({timeoutMs:1000,request:async(input:RequestInfo|URL)=>{const url=String(input);if(url.includes("/cycle")){reachedOld();await oldGate;return json({records:[{id:901,start:"2026-08-15T04:00:00Z",score:{strain:15}}]})}if(url.includes("/recovery")||url.includes("/activity/sleep")||url.includes("/activity/workout"))return json({records:[]});if(url.includes("/measurement/body"))return json({});return json({},404)}});await atOldGate;await whoop.handleCallback("code-three",{timeoutMs:100,request:async(input:RequestInfo|URL)=>String(input).endsWith("/oauth/oauth2/token")?json({access_token:"access-three",refresh_token:"refresh-three",expires_in:3600}):String(input).endsWith("/user/profile/basic")?json({user_id:3,email:"three@example.com",first_name:"Three"}):json({},404)});releaseOld();const switched=await oldPoll;assert.equal(switched.status,"degraded");assert.match(switched.detail,/changed during sync/i);assert.equal((db.getDb().prepare("SELECT COUNT(*) n FROM whoop_daily WHERE day='2026-08-15'").get() as any).n,0);
});

test("poll bounds WHOOP collections to a deterministic recent window and ingests energy",async()=>{
  const {whoop,db}=await setup();setEnabled(db,true);const collectionUrls:URL[]=[];const now="2032-09-17T12:34:56.789Z";
  const request=async(input:RequestInfo|URL)=>{const url=new URL(String(input));if(url.pathname.endsWith("/oauth/oauth2/token"))return json({access_token:"recent-window-access",refresh_token:"recent-window-refresh",expires_in:3600,scope:"offline"});if(url.pathname.endsWith("/user/profile/basic"))return json({user_id:2032,email:"recent-window@example.com",first_name:"Recent Window"});if(url.pathname.endsWith("/cycle")){collectionUrls.push(url);return json({records:[{id:20320917,start:"2032-09-17T04:00:00Z",updated_at:"2032-09-17T11:00:00Z",score:{strain:15.2,kilojoule:1234.5}}]})}if(url.pathname.endsWith("/recovery")){collectionUrls.push(url);return json({records:[]})}if(url.pathname.endsWith("/activity/sleep")){collectionUrls.push(url);return json({records:[]})}if(url.pathname.endsWith("/activity/workout")){collectionUrls.push(url);return json({records:[{id:"recent-window-energy",start:"2032-09-17T08:00:00Z",end:"2032-09-17T09:00:00Z",updated_at:"2032-09-17T09:30:00Z",sport_name:"Cycling",score:{strain:8.4,kilojoule:678.9}}]})}if(url.pathname.endsWith("/measurement/body"))return json({});return json({},404)};
  await whoop.handleCallback("recent-window-code",{request,timeoutMs:100});const result=await whoop.pollWhoop({request,timeoutMs:100,now:()=>now});assert.deepEqual(result,{status:"healthy",detail:"WHOOP sync complete"});
  assert.deepEqual(collectionUrls.map(url=>url.pathname.replace("/developer/v2","")).sort(),["/activity/sleep","/activity/workout","/cycle","/recovery"]);for(const url of collectionUrls){assert.equal(url.searchParams.get("limit"),"25");assert.equal(url.searchParams.get("start"),"2032-08-03T12:34:56.789Z")}
  assert.equal((db.getDb().prepare("SELECT cycle_energy_kj FROM whoop_daily WHERE day='2032-09-17'").get() as any).cycle_energy_kj,1234.5);assert.equal((db.getDb().prepare("SELECT energy_kj FROM health_workouts WHERE source='whoop' AND source_external_id='recent-window-energy' AND deleted_at IS NULL").get() as any).energy_kj,678.9);
});

test("pagination follows next tokens, preserves the original query, enforces its cap, and rejects malformed HTTP 200 payloads",async()=>{const {whoop}=await setup();const urls:string[]=[];const request=async(input:RequestInfo|URL)=>{const url=String(input);urls.push(url);return json(url.includes("nextToken=two")?{records:[{id:2}]}:{records:[{id:1}],next_token:"two"})};const result=await whoop.getWhoopPages("fixture-token","/cycle?limit=1&start=2032-08-03T12%3A34%3A56.789Z",4,{request,timeoutMs:100});assert.deepEqual(result.records,[{id:1},{id:2}]);const second=new URL(urls[1]);assert.equal(second.searchParams.get("nextToken"),"two");assert.equal(second.searchParams.get("limit"),"1");assert.equal(second.searchParams.get("start"),"2032-08-03T12:34:56.789Z");let page=0;await assert.rejects(()=>whoop.getWhoopPages("fixture-token","/cycle?limit=1",2,{request:async()=>json({records:[{id:++page}],next_token:`page-${page}`}),timeoutMs:100}),/pagination exceeded page safety limit/);assert.equal(page,2);await assert.rejects(()=>whoop.getWhoopPages("fixture-token","/cycle?limit=1",4,{request:async()=>json({data:[]}),timeoutMs:100}),/schema/)});

test("explicit upstream null clears an obsolete WHOOP metric while absent siblings remain",async()=>{const {whoop,db}=await setup();setEnabled(db,true);db.getDb().prepare("INSERT OR REPLACE INTO whoop_daily(day,recovery,hrv_ms,rhr_bpm,ts) VALUES ('2026-08-14',70,50,60,'2026-08-14T10:00:00Z')").run();const request=async(input:RequestInfo|URL)=>{const url=String(input);if(url.includes("/cycle"))return json({records:[{id:7,start:"2026-08-14T04:00:00Z",score:{}}]});if(url.includes("/recovery"))return json({records:[{cycle_id:7,created_at:"2026-08-14T12:00:00Z",score:{recovery_score:null}}]});if(url.includes("/activity/sleep")||url.includes("/activity/workout"))return json({records:[]});if(url.includes("/measurement/body"))return json({});return json({},404)};const result=await whoop.pollWhoop({request,timeoutMs:100});assert.equal(result.status,"healthy");assert.deepEqual(db.getDb().prepare("SELECT recovery,hrv_ms,rhr_bpm FROM whoop_daily WHERE day='2026-08-14'").get(),{recovery:null,hrv_ms:50,rhr_bpm:60})});

test("canonical off switch means WHOOP makes zero requests and ingests nothing",async()=>{const {whoop,db}=await setup();setEnabled(db,false);const before=(db.getDb().prepare("SELECT COUNT(*) n FROM whoop_daily").get() as any).n;let calls=0;const result=await whoop.pollWhoop({request:async()=>{calls++;return json({})}});assert.equal(result.status,"disconnected");assert.equal(calls,0);assert.equal((db.getDb().prepare("SELECT COUNT(*) n FROM whoop_daily").get() as any).n,before)});

test("WHOOP disconnect archives active daily rows before clearing them",async()=>{const {whoop,db}=await setup();setEnabled(db,true);db.getDb().prepare("INSERT OR REPLACE INTO whoop_daily(day,recovery,ts) VALUES ('2026-08-22',77,'2026-08-22T12:00:00Z')").run();const before=(db.getDb().prepare("SELECT COUNT(*) n FROM health_whoop_daily_archive").get() as any).n;const activeBefore=(db.getDb().prepare("SELECT COUNT(*) n FROM whoop_daily").get() as any).n;whoop.disconnect();assert.equal((db.getDb().prepare("SELECT COUNT(*) n FROM whoop_daily").get() as any).n,0);const archived=db.getDb().prepare("SELECT reason,day,payload_json FROM health_whoop_daily_archive WHERE day='2026-08-22' ORDER BY id DESC LIMIT 1").get() as any;assert.equal(archived.reason,"disconnect");assert.equal(archived.day,"2026-08-22");assert.equal(JSON.parse(archived.payload_json).recovery,77);assert.equal((db.getDb().prepare("SELECT COUNT(*) n FROM health_whoop_daily_archive").get() as any).n,before+activeBefore)});
