'use client';
import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import Link from 'next/link';
import * as Dialog from '@radix-ui/react-dialog';
import { Plus, ExternalLink, X, Pencil } from 'lucide-react';
import { Button, Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui';
import { SternPage, SternSection, EmptyState, SkeletonRows, SourceBadge, StatusChip } from '@/components/stern/Page';
import { useApi, apiPost } from '@/hooks/useApi';
import { useLiveData } from '@/hooks/useLiveData';
import { ASSIGNMENT_KINDS, ASSIGNMENT_STATUSES, MEETING_KINDS, statusLabel, type SternSnapshot, type CourseDetailData, type Assignment, type GradeCategory, type CourseMeeting } from '@/lib/stern-types';
import { formatDue, percent, WEEKDAYS } from './format';
type Editor={kind:'assignment';item?:Assignment}|{kind:'category';item?:GradeCategory}|{kind:'course'}|{kind:'meeting';item?:CourseMeeting};
type Save=(body:Record<string,unknown>)=>Promise<void>;
export function CourseDetail({courseId}:{courseId:number}){
  const api=useApi<CourseDetailData>(`/api/stern/classes?course=${courseId}`),live=useLiveData<SternSnapshot>('stern');
  const [course,setCourse]=useState<CourseDetailData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editor,setEditor]=useState<Editor|null>(null);
  useEffect(()=>{if(api.data)setCourse(api.data);},[api.data]);
  useEffect(()=>{const c=live?.classes.courses.find(c=>c.id===courseId);if(c)setCourse(c);},[live,courseId]);
  const save:Save=async body=>{setBusy(true);setError('');try{const result=await apiPost('/api/stern/classes',body);const next=result.snapshot.courses.find((c:CourseDetailData)=>c.id===courseId);if(next)setCourse(next);setEditor(null);}catch(e){setError(e instanceof Error?e.message:'Could not save');throw e;}finally{setBusy(false);}};
  if(!course)return <SternPage title="Course" testId="stern-course-detail">{api.error?<EmptyState title="Course could not be loaded" hint={api.error}/>:<SkeletonRows/>}</SternPage>;
  function assignmentList(exams:boolean){const rows=course!.assignments.filter(a=>exams?a.kind==='exam':a.kind!=='exam');return <div className="stern-task-groups" data-testid={exams?'stern-exams-list':'stern-assignments-list'}><Button className="stern-btn" data-testid={exams?'stern-exam-add':'stern-assignment-add'} onClick={()=>setEditor({kind:'assignment'})}><Plus size={14}/>Add assignment</Button>{rows.length?ASSIGNMENT_STATUSES.map(status=>{const group=rows.filter(a=>a.status===status);return group.length?<section key={status}><h2><StatusChip value={status}/><span className="stern-mono">{group.length}</span></h2><div className="stern-row-surface" data-testid={`stern-assignments-${status}`}>{group.map(a=><div className="stern-assignment-row" data-testid="stern-assignment-row" data-assignment-id={a.id} key={a.id}><button className="stern-task-title" data-testid={`stern-assignment-edit-${a.id}`} onClick={()=>setEditor({kind:'assignment',item:a})}>{a.title}</button><span className="stern-type-chip">{statusLabel(a.kind)}</span><time className="stern-mono">{formatDue(a.due_at)}</time><span className="stern-mono">{a.points_earned!==null?`${a.points_earned} / `:''}{a.points_possible??'—'}</span><SourceBadge source={a.source}/></div>)}</div></section>:null;}):<EmptyState title={exams?'No exams added':'No assignments added'} hint="Add an assignment, or let course emails fill in upcoming work."/>}</div>;}
  return <SternPage title={course.title} subtitle={<span className="stern-mono stern-violet">{course.code}</span>} testId="stern-course-detail" actions={<><Link data-testid="stern-course-back" href="/stern/classes" className="stern-btn">All classes</Link><Button data-testid="stern-course-edit" className="stern-btn" onClick={()=>setEditor({kind:'course'})}><Pencil size={13}/>Edit course</Button></>}>
    {error&&!editor&&<p className="stern-recruiting-error" role="alert">{error}</p>}
    <div className="stern-course-header" data-component="CourseHeader"><span>{course.professor?`Prof. ${course.professor}`:'Professor not added'}</span><span>Section <span className="stern-mono">{course.section||'—'}</span></span><span className="stern-mono">{course.room||'Room not added'}</span><span className="stern-mono">{course.credits} credits</span>{(['syllabus_url','brightspace_url'] as const).map(key=>course[key]?<a key={key} data-testid={`stern-course-${key}`} href={course[key]} target="_blank" rel="noreferrer">{key==='syllabus_url'?'Syllabus':'Brightspace'}<ExternalLink size={12}/></a>:<span key={key}>{key==='syllabus_url'?'Syllabus':'Brightspace'} link not added</span>)}</div>
    <Tabs defaultValue="assignments" className="stern-detail-tabs"><TabsList data-testid="stern-course-tabs">{['assignments','exams','grades','notes'].map(tab=><TabsTrigger data-testid={`stern-course-tab-${tab}`} value={tab} key={tab}>{statusLabel(tab)}{['assignments','exams'].includes(tab)&&<span className="stern-mono"> {course.assignments.filter(a=>tab==='exams'?a.kind==='exam':a.kind!=='exam').length}</span>}</TabsTrigger>)}</TabsList>
      <TabsContent value="assignments"><div className="stern-course-columns">{assignmentList(false)}<GradeBook course={course} edit={setEditor}/></div></TabsContent>
      <TabsContent value="exams"><div className="stern-course-columns">{assignmentList(true)}<GradeBook course={course} edit={setEditor}/></div></TabsContent>
      <TabsContent value="grades"><GradeBook course={course} edit={setEditor}/></TabsContent>
      <TabsContent value="notes"><div className="stern-course-columns"><SternSection title="Grading notes"><Notes course={course} save={save} busy={busy}/></SternSection><SternSection title="Meetings" note={<Button data-testid="stern-meeting-add" onClick={()=>setEditor({kind:'meeting'})} size="sm"><Plus size={13}/>Add</Button>}><div data-testid="stern-course-meetings">{course.meetings.length?course.meetings.map(m=><div className="stern-meeting-edit-row" key={m.id}><span className="stern-mono">{WEEKDAYS[m.weekday]} {m.start_time||'Time not added'}{m.end_time?`–${m.end_time}`:''} · {m.room||course.room||'Room not added'}</span><Button data-testid={`stern-meeting-edit-${m.id}`} size="sm" onClick={()=>setEditor({kind:'meeting',item:m})}>Edit</Button></div>):<EmptyState title="No meetings added" hint="Enter known days and times."/>}</div></SternSection></div></TabsContent>
    </Tabs>
    {editor&&<EditorDialog title={editor.kind==='course'?'Edit course':`${'item' in editor&&editor.item?'Edit':'Add'} ${editor.kind}`} close={()=>setEditor(null)} error={error}>
      {editor.kind==='assignment'?<AssignmentForm course={course} item={editor.item} busy={busy} save={save}/>:editor.kind==='category'?<CategoryForm course={course} item={editor.item} busy={busy} save={save}/>:editor.kind==='meeting'?<MeetingForm course={course} item={editor.item} busy={busy} save={save}/>:<CourseForm course={course} busy={busy} save={save}/>}
    </EditorDialog>}
  </SternPage>;
}
function EditorDialog({title,children,close,error}:{title:string;children:ReactNode;close:()=>void;error:string}){return <Dialog.Root open onOpenChange={v=>{if(!v)close();}}><Dialog.Portal><Dialog.Overlay className="stern-course-overlay"/><Dialog.Content className="stern-mode stern-recruiting-dialog" aria-describedby={undefined} data-testid="stern-course-dialog"><header><Dialog.Title>{title}</Dialog.Title><Dialog.Close asChild><button className="stern-text-button" aria-label="Close editor" data-testid="stern-course-dialog-close"><X size={18}/></button></Dialog.Close></header><div className="stern-recruiting-dialog-body">{error&&<p role="alert" className="stern-recruiting-error">{error}</p>}{children}</div></Dialog.Content></Dialog.Portal></Dialog.Root>;}
function GradeBook({course,edit}:{course:CourseDetailData;edit:(editor:Editor)=>void}){const s=course.standing;return <section className="stern-gradebook stern-row-surface" data-testid="stern-gradebook" data-component="GradeBookTable"><header><h2>Grade book</h2><small>weights from syllabus</small></header><div className="stern-gradebook-scroll"><table><thead><tr><th>Category</th><th>Weight</th><th>Earned</th></tr></thead><tbody data-testid="stern-gradebook-categories">{s.categories.map(c=><tr key={c.id}><td><button className="stern-text-button" data-testid={`stern-category-edit-${c.id}`} onClick={()=>edit({kind:'category',item:c})}>{c.name}</button></td><td className="stern-mono">{c.weight_pct}%</td><td className="stern-mono">{c.possible?`${c.earned} / ${c.possible}`:'—'}</td></tr>)}</tbody></table></div>{!s.categories.length&&<EmptyState title="No grade categories" hint="Add syllabus weights, or use the unweighted standing."/>}<footer><strong>Computed standing</strong><span className="stern-mono">{percent(s.percentage)}<small>{s.method==='weighted'?`${s.gradedWeight}% of weight graded`:s.method==='unweighted'?'Unweighted points':''}</small></span></footer>{course.grading_notes&&<p className="stern-curve-note">{course.grading_notes}</p>}<div className="stern-gradebook-actions"><Button data-testid="stern-category-add" size="sm" onClick={()=>edit({kind:'category'})}><Plus size={12}/>Add category</Button></div></section>;}
function Field({label,name,children}:{label:string;name:string;children?:ReactNode}){return <label className="stern-field"><span>{label}</span>{children??<input name={name} data-testid={`stern-${name}`}/>}</label>;}
function val(form:FormData,key:string){return String(form.get(key)??'');}
function numeric(form:FormData,key:string){return val(form,key)===''?null:Number(form.get(key));}
function AssignmentForm({course,item,busy,save}:{course:CourseDetailData;item?:Assignment;busy:boolean;save:Save}){
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),patch={course_id:course.id,title:val(f,'title'),kind:val(f,'kind'),due_at:val(f,'due_at'),status:val(f,'status'),points_possible:numeric(f,'points_possible'),points_earned:numeric(f,'points_earned'),category_id:Number(f.get('category_id')),notes:val(f,'notes')};try{await save(item?{action:'assignment.update',id:item.id,patch}:{action:'assignment.create',assignment:patch});}catch{}}
  return <form className="stern-form-stack" onSubmit={submit} data-testid="stern-assignment-form"><Field label="Title" name="title"><input data-testid="stern-assignment-title" name="title" required defaultValue={item?.title}/></Field><div className="stern-form-grid"><Field label="Type" name="kind"><select data-testid="stern-assignment-kind" name="kind" defaultValue={item?.kind??'homework'}>{ASSIGNMENT_KINDS.map(k=><option key={k} value={k}>{statusLabel(k)}</option>)}</select></Field><Field label="Due (New York)" name="due_at"><input data-testid="stern-assignment-due" name="due_at" type={item?.due_at.includes('T')?'text':'date'} defaultValue={item?.due_at}/></Field><Field label="Status" name="status"><select data-testid="stern-assignment-status" name="status" defaultValue={item?.status??'upcoming'}>{ASSIGNMENT_STATUSES.map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select></Field><Field label="Category" name="category_id"><select data-testid="stern-assignment-category" name="category_id" defaultValue={item?.category_id??0}><option value="0">Uncategorized</option>{course.categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><Field label="Points possible" name="points_possible"><input data-testid="stern-assignment-possible" name="points_possible" type="number" min="0.000001" step="any" defaultValue={item?.points_possible??''}/></Field><Field label="Points earned" name="points_earned"><input data-testid="stern-assignment-earned" name="points_earned" type="number" min="0" step="any" defaultValue={item?.points_earned??''}/></Field></div><Field label="Notes" name="notes"><textarea data-testid="stern-assignment-notes" name="notes" defaultValue={item?.notes}/></Field><Button type="submit" disabled={busy} className="stern-btn primary" data-testid="stern-assignment-save">Save assignment</Button>{item&&<Button type="button" disabled={busy} data-testid="stern-assignment-remove" onClick={()=>void save({action:'assignment.remove',id:item.id}).catch(()=>{})}>Remove assignment</Button>}</form>;
}
function CategoryForm({course,item,busy,save}:{course:CourseDetailData;item?:GradeCategory;busy:boolean;save:Save}){return <form className="stern-form-stack" data-testid="stern-category-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save({action:'category.upsert',category:{...(item?{id:item.id}:{}),course_id:course.id,name:val(f,'name'),weight_pct:Number(f.get('weight_pct')),sort:Number(f.get('sort'))}}).catch(()=>{});}}><Field label="Category name" name="name"><input data-testid="stern-category-name" name="name" required defaultValue={item?.name}/></Field><Field label="Weight (%)" name="weight_pct"><input data-testid="stern-category-weight" name="weight_pct" type="number" min="0" max="100" step="any" required defaultValue={item?.weight_pct??0}/></Field><Field label="Order" name="sort"><input data-testid="stern-category-sort" name="sort" type="number" min="0" defaultValue={item?.sort??0}/></Field><Button disabled={busy} type="submit" className="stern-btn primary" data-testid="stern-category-save">Save category</Button>{item&&<Button type="button" disabled={busy} data-testid="stern-category-remove" onClick={()=>void save({action:'category.remove',id:item.id}).catch(()=>{})}>Remove category</Button>}</form>;}
function Notes({course,save,busy}:{course:CourseDetailData;save:Save;busy:boolean}){return <form className="stern-form-stack" key={course.grading_notes} onSubmit={e=>{e.preventDefault();void save({action:'course.upsert',course:{id:course.id,grading_notes:val(new FormData(e.currentTarget),'notes')}}).catch(()=>{});}}><label className="stern-field">Curve and grading policy<textarea data-testid="stern-course-notes" name="notes" rows={8} defaultValue={course.grading_notes} placeholder="Add notes from the syllabus"/></label><Button type="submit" disabled={busy} data-testid="stern-course-notes-save">Save notes</Button></form>;}
function CourseForm({course,busy,save}:{course:CourseDetailData;busy:boolean;save:Save}){return <form className="stern-form-stack" data-testid="stern-course-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),input:Record<string,unknown>={id:course.id};for(const [k,v] of f)input[k]=k==='credits'?Number(v):v;void save({action:'course.upsert',course:input}).catch(()=>{});}}>{(['code','title','section','professor','professor_email','term','credits','room','syllabus_url','brightspace_url'] as const).map(k=><Field key={k} label={statusLabel(k)} name={k}><input data-testid={`stern-course-field-${k}`} name={k} required={['code','title','term','credits'].includes(k)} type={k==='credits'?'number':k.endsWith('_url')?'url':'text'} defaultValue={course[k]}/></Field>)}<Button type="submit" disabled={busy} className="stern-btn primary" data-testid="stern-course-save">Save course</Button></form>;}
function MeetingForm({course,item,busy,save}:{course:CourseDetailData;item?:CourseMeeting;busy:boolean;save:Save}){return <form className="stern-form-stack" data-testid="stern-meeting-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save({action:'meeting.upsert',meeting:{...(item?{id:item.id}:{}),course_id:course.id,weekday:Number(f.get('weekday')),start_time:val(f,'start_time'),end_time:val(f,'end_time'),room:val(f,'room'),kind:val(f,'kind')}}).catch(()=>{});}}><Field label="Weekday" name="weekday"><select data-testid="stern-meeting-weekday" name="weekday" defaultValue={item?.weekday??1}>{WEEKDAYS.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></Field>{(['start_time','end_time','room'] as const).map(k=><Field label={statusLabel(k)} name={k} key={k}><input data-testid={`stern-meeting-${k}`} name={k} type={k==='room'?'text':'time'} defaultValue={item?.[k]??''}/></Field>)}<Field label="Kind" name="kind"><select data-testid="stern-meeting-kind" name="kind" defaultValue={item?.kind??'lecture'}>{MEETING_KINDS.map(k=><option key={k} value={k}>{statusLabel(k)}</option>)}</select></Field><Button type="submit" disabled={busy} className="stern-btn primary" data-testid="stern-meeting-save">Save meeting</Button>{item&&<Button type="button" disabled={busy} data-testid="stern-meeting-remove" onClick={()=>void save({action:'meeting.remove',id:item.id}).catch(()=>{})}>Remove meeting</Button>}</form>;}
