import { NextResponse } from "next/server";
import { requireUser } from "@/lib/guard";
import { ServiceError, serviceSnapshot, submitServiceVisit } from "@/lib/vending-service";
import { getDb } from "@/db";
export const dynamic="force-dynamic";
const id=(value:string)=>{const n=Number(value);return Number.isInteger(n)&&n>0?n:null};
export async function GET(_:Request,{params}:{params:Promise<{machineId:string}>}){if(!(await requireUser()))return NextResponse.json({error:"unauthorized"},{status:401});try{const machineId=id((await params).machineId);if(!machineId)throw new ServiceError("Invalid machine id.");return NextResponse.json(serviceSnapshot(machineId));}catch(e){const x=e instanceof ServiceError?e:new ServiceError("Could not load service snapshot.",500);return NextResponse.json({error:x.message},{status:x.status});}}
export async function POST(req:Request,{params}:{params:Promise<{machineId:string}>}){const user=await requireUser();if(!user)return NextResponse.json({error:"unauthorized"},{status:401});try{const machineId=id((await params).machineId);if(!machineId)throw new ServiceError("Invalid machine id.");return NextResponse.json(submitServiceVisit(machineId,user.email,await req.json()));}catch(e){const x=e instanceof ServiceError?e:new ServiceError("Service visit could not be saved.",500);return NextResponse.json({error:x.message},{status:x.status});}}
export async function PATCH(req:Request,{params}:{params:Promise<{machineId:string}>}){const user=await requireUser();if(!user)return NextResponse.json({error:"unauthorized"},{status:401});const machineId=id((await params).machineId),body=await req.json(),issueId=Number(body.issueId);if(!machineId||!Number.isInteger(issueId)||issueId<1||typeof body.resolutionNotes!=="string"||!body.resolutionNotes.trim())return NextResponse.json({error:"Issue and resolution notes are required."},{status:400});const result=getDb().prepare(`UPDATE vending_machine_issues SET status='resolved',resolved_by_email=?,resolved_at=?,resolution_notes=? WHERE id=? AND machine_id=? AND status='open'`).run(user.email,new Date().toISOString(),body.resolutionNotes.trim().slice(0,2000),issueId,machineId);return result.changes?NextResponse.json({resolved:true}):NextResponse.json({error:"Open issue not found."},{status:404});}
