"use client";
import { useMemo, useState } from "react";
import { formatCents, formatDate } from "@/lib/pokemon-ops/format";
import type { InventoryRoundBucket, InventoryRoundsSnapshot } from "@/lib/pokemon-ops/inventory-rounds";
import type { PkPurchaseLot } from "@/lib/pokemon-ops/types";
import { BusinessSection, SourceStamp } from "./Page";

type LotRow=PkPurchaseLot&{set_name:string};
const CATEGORIES:Array<{key:"machine"|"stockroom"|"sold"|"unresolved";label:string;color:string}>=[
  {key:"machine",label:"In machine",color:"bg-blue-600"},
  {key:"stockroom",label:"Stockroom",color:"bg-emerald-600"},
  {key:"sold",label:"Sold",color:"bg-violet-600"},
  {key:"unresolved",label:"Unresolved",color:"bg-amber-500"},
];
function money(total:number|null,known:number,knownUnits:number,purchased:number) {
  if (total!==null) return formatCents(total);
  return purchased===0?"No lots yet":`Unknown · ${formatCents(known)} confirmed for ${knownUnits}/${purchased} units`;
}
function Bucket({label,value,color}:{label:string;value:InventoryRoundBucket;color:string}) {
  return <div className="rounded-lg border-2 border-slate-300 bg-white p-3 text-slate-950 shadow-sm">
    <div className="flex items-center gap-2"><span className={`h-3 w-3 rounded-full ${color}`}/><span className="text-xs font-extrabold uppercase tracking-wide text-slate-700">{label}</span></div>
    <strong className="mt-1 block text-2xl text-slate-950">{value.units}</strong><span className="text-sm font-bold text-slate-700">{value.percent}% of purchased</span>
  </div>;
}

export function InventoryRoundsPanel({data,lots,onChanged,error}:{data:InventoryRoundsSnapshot|null;lots:LotRow[];onChanged:()=>void;error:string|null}) {
  const [showCreate,setShowCreate]=useState(false); const [editing,setEditing]=useState<number|null>(null);
  const [name,setName]=useState(""); const [starts,setStarts]=useState(""); const [ends,setEnds]=useState(""); const [notes,setNotes]=useState("");
  const [selected,setSelected]=useState<number[]>([]); const [saving,setSaving]=useState(false); const [saveError,setSaveError]=useState<string|null>(null);
  const ownerByLot=useMemo(()=>new Map((data?.rounds??[]).flatMap(round=>round.lot_ids.map(id=>[id,round.id] as const))),[data]);
  const request=async(body:unknown,method:"POST"|"PATCH")=>{setSaving(true);setSaveError(null);try{const response=await fetch("/api/pokemon-ops/inventory-rounds",{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`Request failed (${response.status})`);onChanged();return true}catch(e){setSaveError(e instanceof Error?e.message:"Could not save inventory round");return false}finally{setSaving(false)}};
  const create=async(event:React.FormEvent)=>{event.preventDefault();if(await request({name,starts_on:starts,ends_on:ends||null,notes:notes||null},"POST")){setName("");setStarts("");setEnds("");setNotes("");setShowCreate(false)}};
  const beginMembership=(roundId:number,ids:number[])=>{setEditing(roundId);setSelected(ids);setSaveError(null)};
  const saveMembership=async()=>{if(editing===null)return;if(await request({id:editing,lot_ids:selected},"PATCH"))setEditing(null)};
  const trace=data?.traceability; const traceTotal=trace?trace.unassigned_purchase_units+trace.unlinked_refill_units+trace.over_allocated_refill_units+trace.unknown_machine_units+trace.unknown_sold_units:0;
  return <>
    <div className="mb-4 rounded-xl border-2 border-slate-300 bg-white p-4 text-slate-950 shadow-sm">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-xs font-extrabold uppercase tracking-wider text-blue-800">Purchase cohort map</span><h2 className="mt-1 text-xl font-black">Inventory rounds</h2><p className="mt-1 max-w-3xl text-sm font-medium text-slate-700">Rounds group canonical purchase lots by when they were bought. Refills do not change round membership. Costs stay on purchase lots, so a round can exist without inventing a dollar amount.</p></div><button className="business-primary-action" onClick={()=>setShowCreate(open=>!open)}>{showCreate?"Close":"New round"}</button></div>
      {showCreate&&<form className="mt-4 grid gap-3 rounded-lg border-2 border-blue-200 bg-blue-50 p-4 sm:grid-cols-2" onSubmit={create}><label className="text-sm font-bold text-slate-900">Round name<input required className="mt-1 w-full rounded-md border-2 border-slate-400 bg-white px-3 py-2 text-slate-950" value={name} onChange={e=>setName(e.target.value)} placeholder="Round 2"/></label><label className="text-sm font-bold text-slate-900">Bought on / starts<input required type="date" className="mt-1 w-full rounded-md border-2 border-slate-400 bg-white px-3 py-2 text-slate-950" value={starts} onChange={e=>setStarts(e.target.value)}/></label><label className="text-sm font-bold text-slate-900">Ends (optional)<input type="date" className="mt-1 w-full rounded-md border-2 border-slate-400 bg-white px-3 py-2 text-slate-950" value={ends} onChange={e=>setEnds(e.target.value)}/></label><label className="text-sm font-bold text-slate-900">Note (optional)<input className="mt-1 w-full rounded-md border-2 border-slate-400 bg-white px-3 py-2 text-slate-950" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="36-pack Pitch Black booster box · cost pending"/></label><div className="sm:col-span-2"><button disabled={saving} className="business-primary-action">{saving?"Saving…":"Create round"}</button></div></form>}
      {saveError&&<p role="alert" className="mt-3 rounded-md border-2 border-red-600 bg-red-50 p-3 text-sm font-bold text-red-900">{saveError}</p>}
    </div>
    {error?<div className="business-empty" role="alert"><h2>Could not load inventory rounds</h2><p>{error}</p></div>:!data?<div className="business-empty" role="status"><h2>Loading inventory rounds</h2><p>Mapping lots, refills, and sales.</p></div>:<>
      {traceTotal>0&&<div className="mb-4 rounded-xl border-2 border-amber-500 bg-amber-50 p-4 text-amber-950" data-testid="round-traceability-warning"><strong className="block text-base">Traceability needs attention</strong><p className="mt-1 text-sm">These quantities are shown separately instead of being guessed into a round.</p><div className="mt-3 grid gap-2 text-sm font-bold sm:grid-cols-2 lg:grid-cols-5"><span>Unassigned purchases: {trace!.unassigned_purchase_units}</span><span>Unlinked refills: {trace!.unlinked_refill_units}</span><span>Excess lot refills: {trace!.over_allocated_refill_units}</span><span>Unknown in machine: {trace!.unknown_machine_units}</span><span>Unattributed sold: {trace!.unknown_sold_units}</span></div></div>}
      {data.rounds.length===0?<div className="business-empty"><h2>No inventory rounds yet</h2><p>Create a dated round, then map existing purchase lots into it. Purchase lots remain the inventory source of truth.</p></div>:<div className="grid gap-5 xl:grid-cols-2">{data.rounds.map(round=><article key={round.id} className="overflow-hidden rounded-xl border-2 border-slate-300 bg-slate-100 text-slate-950 shadow-md" data-testid={`inventory-round-${round.id}`}>
        <header className="border-b-2 border-slate-300 bg-slate-950 p-4 text-white"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-xs font-extrabold uppercase tracking-wider text-blue-200">{formatDate(round.starts_on)}{round.ends_on?` – ${formatDate(round.ends_on)}`:" onward"}</span><h2 className="mt-1 text-2xl font-black">{round.name}</h2><p className="mt-1 text-sm text-slate-200">{round.notes||"No round note"}</p></div><button className="rounded-md border-2 border-white bg-white px-3 py-2 text-sm font-black text-slate-950" onClick={()=>beginMembership(round.id,round.lot_ids)}>Manage lots</button></div><div className="mt-4 grid grid-cols-2 gap-3"><div><span className="block text-xs font-bold uppercase text-slate-300">Purchased</span><strong className="text-2xl">{round.totals.purchased_units} units</strong></div><div><span className="block text-xs font-bold uppercase text-slate-300">Total cost</span><strong className="text-lg">{money(round.totals.total_cost_cents,round.totals.known_cost_cents,round.totals.known_cost_units,round.totals.purchased_units)}</strong></div></div></header>
        <div className="grid grid-cols-2 gap-2 p-3 sm:grid-cols-4">{CATEGORIES.map(category=><Bucket key={category.key} label={category.label} value={round.totals[category.key]} color={category.color}/>)}</div>
        <div className="border-t-2 border-slate-300 bg-white p-4"><h3 className="text-sm font-extrabold uppercase tracking-wide text-slate-700">Products · {round.lot_count} canonical {round.lot_count===1?"lot":"lots"}</h3>{round.products.length===0?<p className="mt-2 text-sm font-semibold text-slate-600">No purchase lots mapped yet.</p>:<div className="mt-2 space-y-2">{round.products.map(product=><div key={product.product_id} className="rounded-md border border-slate-300 bg-slate-50 p-3"><div className="flex flex-wrap justify-between gap-2"><strong>{product.display_name}</strong><span className="rounded-full bg-slate-900 px-2 py-0.5 text-xs font-bold text-white">{product.form.replaceAll("_"," ")}</span></div><p className="mt-1 text-xs font-semibold text-slate-700">{product.purchased_units} bought · {product.machine.units} machine · {product.stockroom.units} stockroom · {product.sold.units} sold{product.unresolved.units?` · ${product.unresolved.units} unresolved`:""}</p></div>)}</div>}</div>
        {editing===round.id&&<div className="border-t-2 border-blue-300 bg-blue-50 p-4"><h3 className="font-black">Map purchase lots to {round.name}</h3><p className="mt-1 text-sm font-medium text-slate-700">Only lots bought within this round’s dates can be saved. A lot can belong to one round.</p><div className="mt-3 max-h-64 space-y-2 overflow-auto">{lots.filter(lot=>{const owner=ownerByLot.get(lot.id);return owner===undefined||owner===round.id}).map(lot=><label key={lot.id} className="flex cursor-pointer items-start gap-3 rounded-md border-2 border-slate-300 bg-white p-3"><input type="checkbox" className="mt-1 h-4 w-4" checked={selected.includes(lot.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,lot.id]:ids.filter(id=>id!==lot.id))}/><span><strong className="block">{lot.set_name} · {lot.pack_count} units</strong><small className="font-semibold text-slate-700">Bought {formatDate(lot.purchase_date)} · {lot.cost_confirmed?formatCents(lot.total_cost_cents):"Cost pending"} · lot #{lot.id}</small></span></label>)}</div><div className="mt-3 flex gap-2"><button disabled={saving} className="business-primary-action" onClick={saveMembership}>{saving?"Saving…":"Save membership"}</button><button className="rounded-md border-2 border-slate-500 bg-white px-3 py-2 text-sm font-bold" onClick={()=>setEditing(null)}>Cancel</button></div></div>}
      </article>)}</div>}
      <div className="mt-4"><BusinessSection title="How attribution works" note={<SourceStamp>deterministic · bounded · no invented quantities</SourceStamp>}><div className="grid gap-3 text-sm sm:grid-cols-3"><p><strong className="block text-txt">Round membership</strong>Uses each canonical lot’s purchase date, never its machine refill date.</p><p><strong className="block text-txt">Mixed refills and sales</strong>Uses `pk_stock_events.lot_id`, then FIFO by lot purchase date and ID within each product.</p><p><strong className="block text-txt">Unknown evidence</strong>Unlinked, excess, audit-only, or otherwise untraceable quantities remain explicitly unresolved.</p></div></BusinessSection></div>
    </>}
  </>;
}
