'use client';
import { useState, type FormEvent } from 'react';
import { Settings2, RefreshCw, CalendarDays } from 'lucide-react';
import { Button } from '@/components/ui';
import { useApi } from '@/hooks/useApi';
import { useLiveData } from '@/hooks/useLiveData';
import { SternPage, SternSection, SkeletonRows, EmptyState, StatusChip, SourceBadge } from '../Page';
import { STERN_SETTINGS_DEFAULTS, statusLabel, type SternSnapshot, type SternAutomationResponse, type SternConnectionCard, type SternNotificationSettings, type SternReminder } from '@/lib/stern-types';
import { SternDialog, AuditLogRows, ActionNotice, useAutomationAction } from './shared';
import { dateLabel } from '../recruiting/Controls';

export function ConnectionCard({card}:{card:SternConnectionCard}) {
  const google=card.id.includes('google');
  const label=card.state==='on_healthy'?'Connected':card.state==='on_broken'?(google?'Needs re-auth':'Needs attention'):'Not connected';
  return <article className="stern-connection-card" data-component="ConnectionCard" data-testid={`stern-connection-${card.id}`} data-state={card.state}>
    <header><strong>{card.label}</strong><StatusChip value={card.state} label={label}/></header>
    <p className="stern-muted">{card.account||(google?'No account connected':card.id==='hermes'?'Hermes gateway':'ChatGPT subscription')}</p>
    <div className="stern-scope-list" data-testid={`stern-scopes-${card.id}`}>{card.scopes.length?card.scopes.map(s=><span className="stern-mono" key={s}>{s}</span>):<span className="stern-muted">{google?'No scopes granted':card.id==='hermes'?'Agent gateway health':'Local Codex CLI'}</span>}</div>
    <p className="stern-muted">{card.detail}</p>
    <footer><span className="stern-muted">{card.id==='career-google-personal'?'Last inbox sync':google?'Last scan':'Last checked'} <span className="stern-mono">{card.lastScan?dateLabel(card.lastScan,true):'Never'}</span></span><a className="stern-btn" data-testid={`stern-reconnect-${card.id}`} href={card.reconnectHref}>{google?(card.account?'Reconnect':'Connect'):'Manage'}</a></footer>
  </article>;
}
function reminderText(row:SternReminder) { try {const m=JSON.parse(row.message);return {subject:String(m.subject||statusLabel(row.rule_key)),body:String(m.body||'')};} catch {return {subject:statusLabel(row.rule_key),body:row.message};} }
const SETTINGS: [keyof SternNotificationSettings,string,string][]=[['stern.threshold_auto','Auto-apply threshold','number'],['stern.threshold_suggest','Suggestion threshold','number'],['stern.memo_email','Memo email','email'],['stern.imessage_target','iMessage target','text'],['stern.hermes_alias','Hermes alias','text'],['stern.quiet_hours_start','Quiet hours start (New York)','time'],['stern.quiet_hours_end','Quiet hours end (New York)','time']];
export function AutomationView() {
  const api=useApi<SternAutomationResponse>('/api/stern/automation'),live=useLiveData<SternSnapshot>('stern');
  const [saved,setSaved]=useState<SternAutomationResponse|null>(null),[settingsOpen,setSettingsOpen]=useState(false),[settings,setSettings]=useState<SternNotificationSettings|null>(null),[copyError,setCopyError]=useState('');
  const action=useAutomationAction(r=>{setSaved({...r,updatedAt:r.snapshot.updatedAt});});
  const base=saved&&(!api.data||saved.updatedAt>api.data.updatedAt)?saved:api.data;
  const data=base&&live&&live.updatedAt>base.updatedAt?{...base,...live.automation}:base;
  async function saveSettings(e:FormEvent) {e.preventDefault();if(await action.act({action:'settings.update',settings}))setSettingsOpen(false);}
  async function copyDraft(id:number,body:string){setCopyError('');try{await navigator.clipboard.writeText(body);await action.act({action:'draft.mark_copied',id});}catch{setCopyError('Clipboard unavailable. Select and copy the draft text.');}}
  if (!data && api.error) return <SternPage title="Automation" testId="stern-automation"><EmptyState title="Automation could not be loaded" hint={api.error} action={<Button className="stern-btn" data-testid="stern-automation-retry" onClick={api.refetch}>Retry</Button>}/></SternPage>;
  return <SternPage title="Automation" testId="stern-automation" actions={<><Button className="stern-btn" data-testid="stern-scan-now" disabled={action.busy} onClick={()=>void action.act({action:'scan.now'})}><RefreshCw size={14}/>Scan now</Button><Button className="stern-btn" data-testid="stern-calendar-sync-now" disabled={action.busy} onClick={()=>void action.act({action:'calendar.sync_now'})}><CalendarDays size={14}/>Sync calendar now</Button><Button className="stern-btn" data-testid="stern-settings-open" disabled={!data} onClick={()=>{setSettings(data!.notificationSettings);setSettingsOpen(true);}}><Settings2 size={14}/>Settings</Button></>}>
    <ActionNotice error={action.error||copyError||api.error||''} message={action.message}/>
    {data?.connectHref&&<div className="stern-connect-banner" data-testid="stern-connect-banner"><span>Connect your Stern account to bring email and calendar into Stern.</span><a href={data.connectHref} className="stern-btn primary" data-testid="stern-connect-account">Connect Stern Google</a></div>}
    <div className="stern-connection-grid" data-testid="stern-connections-list">{data?data.connections.map(card=><ConnectionCard key={card.id} card={card}/>):[1,2,3,4,5].map(i=><SkeletonRows key={i} rows={4}/>)}</div>
    <SternSection title="Suggestions" note="Not confident enough to auto-apply" testId="stern-suggestions"><div className="stern-suggestion-grid" data-testid="stern-suggestions-list">{!data?<SkeletonRows/>:!data.suggestions.length?<EmptyState title="No suggestions waiting for review" hint="Uncertain detections appear here with evidence before anything changes."/>:data.suggestions.map(s=><article className="stern-suggestion-card" id={`suggestion-${s.id}`} key={s.id} data-component="SuggestionCard" data-testid={`stern-suggestion-${s.id}`}><header><strong>{s.summary}</strong><SourceBadge source="suggested"/></header><p>{s.evidence_subject||'Untitled source message'}</p><blockquote className="stern-evidence">{s.evidence_excerpt||'No excerpt available'}<small className="stern-mono">{s.evidence_type==='gmail'?`Gmail${s.gmail_account?` · ${s.gmail_account}`:''}`:s.evidence_type==='imessage'?'iMessage':statusLabel(s.evidence_type)} · {dateLabel(s.created_at,true)} · Confidence {s.confidence.toFixed(2)}</small></blockquote><details><summary data-testid={`stern-suggestion-details-${s.id}`}>Proposed change</summary><pre>{s.proposed_data}</pre></details><div className="stern-button-row"><Button className="stern-btn primary" disabled={action.busy} data-testid={`stern-suggestion-accept-${s.id}`} onClick={()=>void action.act({action:'suggestion.accept',id:s.id})}>Accept</Button><Button className="stern-btn ghost" disabled={action.busy} data-testid={`stern-suggestion-dismiss-${s.id}`} onClick={()=>void action.act({action:'suggestion.dismiss',id:s.id})}>Dismiss</Button></div></article>)}</div></SternSection>
    <SternSection title="Audit log" note="Latest 100 changes · Undo applies to the whole batch" flush testId="stern-automation-audit">{data?<AuditLogRows rows={data.audit} busy={action.busy} undo={batchId=>void action.act({action:'batch.undo',batchId})}/>:<SkeletonRows/>}</SternSection>
    <SternSection title="Reminders" testId="stern-reminders" note={<Button className="stern-btn" data-testid="stern-reminder-test" disabled={action.busy} onClick={()=>void action.act({action:'reminder.send_test'})}>Send test</Button>}><div id="reminders" data-testid="stern-reminders-list">{!data?<SkeletonRows/>:!data.reminders.length?<EmptyState title="No reminders yet" hint="Scheduled reminders and delivery attempts appear here."/>:data.reminders.map(r=>{const m=reminderText(r);return <article className="stern-reminder-row" data-testid={`stern-reminder-${r.id}`} key={r.id}><div><strong>{m.subject}</strong><p>{m.body}</p><small className="stern-muted"><span className="stern-mono">{dateLabel(r.fire_at,true)}</span> · {r.channel}{r.error&&` · ${r.error==='dry-run'?'Dry run, nothing delivered':r.error}`}</small></div><StatusChip value={r.delivery_status} label={r.error==='dry-run'?'Skipped (dry run)':undefined}/>{['pending','snoozed'].includes(r.delivery_status)&&<Button className="stern-btn" disabled={action.busy} data-testid={`stern-reminder-snooze-${r.id}`} onClick={()=>void action.act({action:'reminder.snooze',id:r.id,until:new Date(Math.max(Date.now(),Date.parse(r.fire_at))+3600000).toISOString()})}>Snooze 1h</Button>}</article>;})}</div></SternSection>
    <SternSection title="Drafts" note="Review and copy, or create a Gmail draft" testId="stern-drafts"><div className="stern-suggestion-grid" data-testid="stern-drafts-list">{!data?<SkeletonRows/>:!data.drafts.length?<EmptyState title="No drafts ready" hint="Request, reply, and thank-you drafts appear when a chat needs one."/>:data.drafts.map(d=><article className="stern-suggestion-card" key={d.id} id={`draft-${d.id}`} data-testid={`stern-draft-${d.id}`}><header><strong>{d.subject}</strong><StatusChip value={d.state}/></header><span className="stern-muted">To: {d.to_email||'No email address'}</span><pre className="stern-draft-body">{d.body}</pre><div className="stern-button-row"><Button className="stern-btn" disabled={action.busy} data-testid={`stern-draft-copy-${d.id}`} onClick={()=>void copyDraft(d.id,d.body)}>Copy</Button><Button className="stern-btn" disabled={action.busy} data-testid={`stern-draft-gmail-${d.id}`} onClick={()=>void action.act({action:'draft.create_gmail_draft',id:d.id})}>Create Gmail draft</Button><Button className="stern-btn ghost" disabled={action.busy} data-testid={`stern-draft-regenerate-${d.id}`} onClick={()=>void action.act({action:'draft.regenerate',id:d.id})}>Regenerate</Button></div></article>)}</div></SternSection>
    {settingsOpen&&settings&&<SternDialog drawer title="Automation settings" onClose={()=>setSettingsOpen(false)}><form onSubmit={saveSettings} className="stern-settings-form">{SETTINGS.map(([key,label,type])=><label className="stern-field" key={key}><span>{label}</span><input className={`stern-input ${type==='number'||type==='time'?'stern-mono':''}`} data-testid={`stern-setting-${key.split('.').pop()}`} type={type} min={type==='number'?0:undefined} max={type==='number'?1:undefined} step={type==='number'?'any':undefined} required={key!=='stern.imessage_target'} value={settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.value})}/></label>)}<fieldset><legend>Confidence thresholds</legend><p className="stern-muted">Defaults: Auto-apply ≥ <span className="stern-mono">{STERN_SETTINGS_DEFAULTS.thresholdAuto}</span> · Suggest ≥ <span className="stern-mono">{STERN_SETTINGS_DEFAULTS.thresholdSuggest}</span></p><small className="stern-muted">Defaults shown above. Suggestion threshold must not exceed auto-apply.</small></fieldset><ActionNotice error={action.error} message=""/><Button className="stern-btn primary" type="submit" disabled={action.busy} data-testid="stern-settings-save">Save settings</Button></form></SternDialog>}
  </SternPage>;
}
