'use client';
import { useState } from 'react';
import * as Switch from '@radix-ui/react-switch';
import { PersonRow, CoffeeChatChip } from '../recruiting/People';
import { AssignmentRow } from '../classes/AssignmentRow';
import { Button, Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui';
import { SternPage, SternSection, StatusChip, SourceBadge, StrengthDots, StatTile, SkeletonRows, EmptyState } from '../Page';
import * as T from '@/lib/stern-types';
import { ConnectionCard } from './AutomationView';
import { SternDialog, ActionNotice } from './shared';
const groups=[['Process',T.PROCESS_STATUSES],['Club',T.CLUB_STATUSES],['Program',T.PROGRAM_STATUSES],['Coffee chat',T.COFFEE_CHAT_STATES],['Person',T.PERSON_STATUSES],['Relationship',T.RELATIONSHIP_TYPES],['Task',T.TASK_STATUSES],['Task domain',T.TASK_DOMAINS],['Assignment',T.ASSIGNMENT_STATUSES],['Draft',T.DRAFT_STATES],['Suggestion',T.SUGGESTION_STATES],['Email',T.EMAIL_APPLIED_STATES],['Reminder',T.REMINDER_DELIVERY_STATUSES]] as const;
export function ComponentSheet(){
  const [dialog,setDialog]=useState(false),[strength,setStrength]=useState(3),[toast,setToast]=useState(true),[enabled,setEnabled]=useState(true),[disabledToggle,setDisabledToggle]=useState(false);
  return <SternPage title="Component sheet" subtitle="Development preview · placeholder data only" testId="stern-component-sheet">
    <div className="stern-component-grid"><SternSection title="Status vocabulary"><div data-testid="stern-component-statuses">{groups.map(([label,values])=><div className="stern-component-group" key={label}><h3>{label}</h3><div className="stern-button-row">{values.map(v=><StatusChip key={v} value={v}/>)}</div></div>)}</div></SternSection>
    <div className="stern-component-stack"><SternSection title="Sources and strength"><div className="stern-button-row" data-testid="stern-component-sources">{T.SOURCE_BADGE_KINDS.map(s=><SourceBadge key={s} source={s==='auto_imessage'?'imessage':s}/>)}</div><div className="stern-button-row" data-testid="stern-component-dots">{['ok','warn','error','info','off'].map(state=><span className="stern-preview-control" key={state}><i className="stern-preview-dot" style={{background:`var(--stern-${state})`}}/>{T.statusLabel(state)}</span>)}<b className="stern-network-eboard">E-board</b><span className="stern-type-chip">Finance</span></div><StrengthDots value={strength} editable onChange={setStrength}/></SternSection>
    <SternSection title="Buttons, fields, and dialog"><div className="stern-button-row"><Button className="stern-btn primary" data-testid="stern-component-primary" onClick={()=>setDialog(true)}>Open dialog</Button><Button className="stern-btn" data-testid="stern-component-secondary" onClick={()=>setToast(true)}>Show notice</Button><Button className="stern-btn ghost" data-testid="stern-component-ghost" onClick={()=>setToast(true)}>Ghost</Button><Button className="stern-btn small" size="sm" data-testid="stern-component-small" onClick={()=>setToast(true)}>Small</Button><Button className="stern-btn" disabled data-testid="stern-component-disabled">Disabled</Button></div><label className="stern-field"><span>Example input</span><input className="stern-input" data-testid="stern-component-input" placeholder="Search people, clubs, tasks"/></label><label className="stern-field"><span>Focused input</span><input className="stern-input stern-preview-focus" data-testid="stern-component-focused-input" defaultValue="Example Person"/></label>
    <label className="stern-field"><span>Invalid input</span><input className="stern-input" data-testid="stern-component-invalid-input" aria-invalid="true" aria-describedby="stern-component-input-error" defaultValue="1.2"/><small id="stern-component-input-error" className="stern-recruiting-error">Threshold must be between 0 and 1.</small></label>
    <label className="stern-field"><span>Task domain</span><select className="stern-select" data-testid="stern-component-select">{T.TASK_DOMAINS.map(d=><option key={d}>{T.statusLabel(d)}</option>)}</select></label>
    <div className="stern-button-row">{[[enabled,setEnabled,'on'],[disabledToggle,setDisabledToggle,'off']].map(([value,change,label])=><label key={String(label)} className="stern-preview-control">Toggle {String(label)}<Switch.Root className="stern-preview-switch" checked={value as boolean} onCheckedChange={change as (v:boolean)=>void} data-testid={`stern-component-toggle-${label}`}><Switch.Thumb/></Switch.Root></label>)}<label><input type="checkbox" defaultChecked data-testid="stern-component-checkbox"/> Example checkbox</label></div>
    <Tabs defaultValue="people" className="stern-detail-tabs"><TabsList data-testid="stern-component-tabs"><TabsTrigger value="people" data-testid="stern-component-tab-people">People</TabsTrigger><TabsTrigger value="tasks" data-testid="stern-component-tab-tasks">Tasks</TabsTrigger></TabsList><TabsContent value="people">Example people tab</TabsContent><TabsContent value="tasks">Example tasks tab</TabsContent></Tabs>
    {toast&&<ActionNotice error="" message={<>Auto-applied: Example Person marked Replied. <button className="stern-text-button" data-testid="stern-component-undo" onClick={()=>setToast(false)}>Undo</button></>}/>}</SternSection>
    <SternSection title="StatTile and skeleton"><div className="stern-stat-grid"><StatTile label="Coffee chats owed" value={3} tone="warn" sub="2 replies waiting"/><SkeletonRows rows={3}/></div></SternSection>
    <SternSection title="Empty and error states"><EmptyState title="No people yet" hint="Text the Stern bot or use Quick add."/><p className="stern-recruiting-error" role="alert">Example: Gmail could not be reached.</p><StatusChip value="skipped" label="Skipped (dry run)"/></SternSection>
    <SternSection title="Person and assignment rows"><div data-testid="stern-component-rows" className="stern-component-stack">{['Normal','Selected','Hover'].map((state,i)=><div key={state}><h3>{state}</h3><PersonRow person={{display_name:'Example Person',role:'E-board',title:'',year:'Sophomore',chat:null}} selected={i===1} hovered={i===2}><div className="stern-person-actions"><Button className="stern-btn" data-testid={`stern-component-person-action-${i}`} onClick={()=>setToast(true)}>Draft email</Button></div></PersonRow></div>)}{T.COFFEE_CHAT_STATES.map(state=><CoffeeChatChip key={state} chat={{state} as T.CoffeeChat}/>)}{T.ASSIGNMENT_STATUSES.map((status,i)=><div key={status}><StatusChip value={status}/><AssignmentRow assignment={{id:i+1,title:'Example assignment',kind:'homework',due_at:'2026-09-12',points_earned:status==='graded'?18:null,points_possible:20,source:'manual'}} selected={i===1} hovered={i===2} onEdit={()=>setDialog(true)}/></div>)}</div></SternSection></div></div>
    <div className="stern-connection-grid" data-testid="stern-component-connections">{['on_healthy','on_broken','off'].map(state=><ConnectionCard key={state} card={{id:`preview-google-${state}`,label:'Example Gmail',state,detail:'Development status preview',account:'example@example.com',scopes:['gmail.readonly'],lastScan:'',reconnectHref:'#'}}/>)}</div>
    {dialog&&<SternDialog title="Example dialog" onClose={()=>setDialog(false)}><p>Escape closes this dialog and restores focus.</p><Button className="stern-btn primary" data-testid="stern-component-dialog-done" onClick={()=>setDialog(false)}>Done</Button></SternDialog>}
  </SternPage>;
}
