"use client";
import Link from "next/link";
import { useState } from "react";
import { Archive, ArrowLeft, Plus } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui";
import { SternPage, SternSection, EmptyState, SkeletonRows, SourceBadge, StatusChip } from "@/components/stern/Page";
import { CLUB_CATEGORIES, CLUB_TRANSITIONS, PROGRAM_TRACKS, statusLabel, type RecruitingActivity, type RecruitingClubDetail } from "@/lib/stern-types";
import { DeadlineStrip } from "@/components/stern/DeadlineStrip";
import { useRecruiting, type RecruitingMutation } from "./useRecruiting";
import { RecruitingButton, RecruitingDialog, PriorityStars, StatusSelect, SafeLink, dateLabel, Field, MutationNotice } from "./Controls";
import { ProgramCard } from "./ProgramCard";
import { People } from "./People";

function Activity({ rows, undo, busy }: { rows: RecruitingActivity[]; undo: (batchId: string) => void; busy: boolean }) {
  return !rows.length ? <EmptyState title="No activity recorded yet" hint="Changes and conversations with this club's people appear here."/> : <ol className="stern-activity-list" data-component="TouchpointTimeline" data-testid="stern-club-activity-list">{rows.map(item => <li key={item.key}><div><strong>{item.summary}</strong><span><time className="stern-mono">{dateLabel(item.at, true)}</time><SourceBadge source={item.source}/>{item.undone_at && <small>Undone</small>}</span></div>{item.batch_id && !item.undone_at && <RecruitingButton data-testid={`stern-activity-undo-${item.id}`} disabled={busy} onClick={() => undo(item.batch_id)}>Undo batch</RecruitingButton>}</li>)}</ol>;
}
function InterviewPrep({ club, disabled, mutate }: { club: RecruitingClubDetail; disabled: boolean; mutate: RecruitingMutation }) {
  return <div className="stern-detail-columns"><div className="stern-stack">
    {club.programs.map(program => <SternSection key={program.id} title={program.name}>
      <form className="stern-inline-form" onSubmit={async e => { e.preventDefault(); await mutate({ action: "program.upsert", program: { id: program.id, dress_code: new FormData(e.currentTarget).get("dress_code") } }); }}><Field label="Interview dress code"><input className="stern-input" name="dress_code" data-testid={`stern-prep-dress-${program.id}`} defaultValue={program.dress_code} key={program.dress_code} disabled={disabled}/></Field><RecruitingButton data-testid={`stern-prep-dress-save-${program.id}`} type="submit" disabled={disabled}>Save</RecruitingButton></form>
      {!club.prep.some(p => p.program_id === program.id) && <EmptyState title="No interview questions yet" hint="Add a question and prepare your answer below."/>}
      <div className="stern-prep-list" data-testid={`stern-prep-list-${program.id}`}>{club.prep.filter(p => p.program_id === program.id).map(prep => <form key={prep.id} className="stern-prep-row" onSubmit={async e => { e.preventDefault(); const fields = Object.fromEntries(new FormData(e.currentTarget)); await mutate({ action: "prep.upsert", prep: { id: prep.id, ...fields, sort: Number(fields.sort) } }); }}><fieldset disabled={disabled}>
        <Field label="Question"><input required className="stern-input" name="question" data-testid={`stern-prep-question-${prep.id}`} defaultValue={prep.question} key={prep.question}/></Field><Field label="Answer"><textarea className="stern-textarea" rows={4} name="answer" data-testid={`stern-prep-answer-${prep.id}`} defaultValue={prep.answer} key={prep.answer}/></Field><Field label="Order"><input className="stern-input stern-mono" type="number" min={0} name="sort" data-testid={`stern-prep-sort-${prep.id}`} defaultValue={prep.sort} key={prep.sort}/></Field><RecruitingButton type="submit" data-testid={`stern-prep-save-${prep.id}`}>Save answer</RecruitingButton>
      </fieldset></form>)}</div>
      <form className="stern-prep-row" onSubmit={async e => { e.preventDefault(); const form = e.currentTarget; if (await mutate({ action: "prep.upsert", prep: { program_id: program.id, ...Object.fromEntries(new FormData(form)), sort: club.prep.length } })) form.reset(); }}><fieldset disabled={disabled}><Field label="New question"><input required name="question" className="stern-input" data-testid={`stern-prep-new-question-${program.id}`} placeholder="What would you like to practice?"/></Field><Field label="Answer"><textarea name="answer" className="stern-textarea" rows={3} data-testid={`stern-prep-new-answer-${program.id}`}/></Field><RecruitingButton primary type="submit" data-testid={`stern-prep-add-${program.id}`}><Plus size={14}/>Add question</RecruitingButton></fieldset></form>
    </SternSection>)}
    {!club.programs.length && <EmptyState title="No programs to prepare for" hint="Add a program in Application first."/>}
  </div><SternSection title="From your coffee chats"><div className="stern-quotes" data-testid="stern-prep-quotes">{club.chats.some(c => c.takeaways) ? club.chats.filter(c => c.takeaways).map(chat => <blockquote key={chat.id}><p>{chat.takeaways}</p><footer>{club.people.find(p => p.id === chat.person_id)?.display_name || "Club contact"} · <span className="stern-mono">{dateLabel(chat.occurred_at)}</span></footer></blockquote>) : <EmptyState title="No coffee chat takeaways yet" hint="Save takeaways in People to bring them into interview prep."/>}</div></SternSection></div>;
}
export function ClubDetail({ clubId, draftsAvailable }: { clubId: number; draftsAvailable: boolean }) {
  const state = useRecruiting(); const { snapshot, busy, mutate } = state;
  const club = snapshot?.clubs.find(c => c.id === clubId);
  const catalogClub = snapshot?.catalog.find(c => c.id === clubId);
  const [archiving, setArchiving] = useState(false); const [addingProgram, setAddingProgram] = useState(false);
  if (!snapshot) return <SternPage title="Club recruiting" testId="stern-club-detail">{state.error ? <EmptyState title="Could not load this club" hint={state.error} action={<RecruitingButton data-testid="stern-detail-retry" onClick={state.refetch}>Retry</RecruitingButton>}/> : <SkeletonRows rows={10}/>}</SternPage>;
  if (!club) return <SternPage title={catalogClub?.name || "Club not found"} testId="stern-club-detail"><MutationNotice {...state} undo={() => void state.undo()}/><EmptyState title={catalogClub ? "This club is not on your board" : "This club does not exist"} hint={catalogClub ? "Add it to your recruiting board to view its programs and checklist." : "Return to recruiting to choose a club."} action={catalogClub && catalogClub.status !== "archived" ? <RecruitingButton primary disabled={busy} data-testid="stern-detail-track-club" onClick={() => void mutate({ action: "club.set_interested", clubId, interested: true })}>Track this club</RecruitingButton> : <Link data-testid="stern-detail-back" href="/stern/recruiting">Back to recruiting</Link>}/></SternPage>;
  const disabled = busy || club.status === "archived" || snapshot.process?.status === "archived";
  return <SternPage title={club.name} testId="stern-club-detail" actions={<><StatusChip value={club.status}/><PriorityStars priority={club.priority} disabled={disabled} onChange={priority => void mutate({ action: "club.update", clubId, patch: { priority } })}/><RecruitingButton data-testid="stern-club-archive" disabled={disabled} onClick={() => setArchiving(true)}><Archive size={14}/>Archive</RecruitingButton></>}>
    <div className="stern-club-links"><Link data-testid="stern-detail-back" href="/stern/recruiting"><ArrowLeft size={14}/>Club Recruiting</Link><span className="stern-note-chip">{statusLabel(club.category) || "Uncategorized"}</span><SafeLink testId="stern-club-website" href={club.website}>Website</SafeLink>{club.instagram && <SafeLink testId="stern-club-instagram" href={/^https?:/.test(club.instagram) ? club.instagram : `https://www.instagram.com/${encodeURIComponent(club.instagram.replace(/^@/,""))}/`}>Instagram</SafeLink>}<StatusSelect testId="stern-club-status" label="Club status" value={club.status} choices={CLUB_TRANSITIONS[club.status]} disabled={disabled} onChange={status => void mutate({ action: "club.set_status", clubId, status })}/></div>
    <MutationNotice {...state} undo={() => void state.undo()}/>
    {club.status === "archived" && <p className="stern-muted">Archived. History is preserved; use Undo on the archive activity to resume this club.</p>}
    <Tabs defaultValue="overview" className="stern-detail-tabs">
      <TabsList data-testid="stern-club-detail-tabs" aria-label="Club detail tabs">{[["overview","Overview"],["people","People"],["application","Application"],["prep","Interview prep"],["timeline","Timeline"]].map(([value,label]) => <TabsTrigger data-testid={`stern-club-tab-${value}`} key={value} value={value}>{label}</TabsTrigger>)}</TabsList>
      <TabsContent value="overview"><div className="stern-detail-columns"><div className="stern-stack"><div className="stern-program-grid" data-testid="stern-program-list">{club.programs.map(program => <ProgramCard key={program.id} program={program} disabled={disabled} mutate={mutate}/>)}</div>{!club.programs.length && <EmptyState title="No programs added yet" hint="Use Application to add the club's programs."/>}
        <SternSection title="Checklist" note={<span className="stern-mono">{club.checklistDone} of {club.checklistTotal}</span>} flush>{!club.checklist.length ? <EmptyState title="No checklist items yet" hint="Tracking a club creates the recruiting checklist."/> : <div data-testid="stern-checklist-list">{club.checklist.map(item => <label className="stern-checklist-item" data-component="ChecklistItem" data-testid="stern-checklist-item" key={item.id}><input data-testid={`stern-checklist-toggle-${item.id}`} type="checkbox" disabled={disabled} checked={!!item.done_at} onChange={e => void mutate({ action: "checklist.toggle", itemId: item.id, done: e.target.checked })}/><span className={item.done_at ? "done" : ""}>{item.label}</span><time className="stern-mono">{item.done_at ? dateLabel(item.done_at) : ""}</time></label>)}</div>}</SternSection>
        <SternSection title="Club details"><form className="stern-form-stack" onSubmit={async e => { e.preventDefault(); const fields = Object.fromEntries(new FormData(e.currentTarget)); await mutate({ action: "club.update", clubId, patch: { ...fields, target_chats: Number(fields.target_chats) } }); }}><fieldset disabled={disabled}>
          <Field label="Club name"><input className="stern-input" name="name" data-testid="stern-club-name" required defaultValue={club.name} key={club.name}/></Field><Field label="Category"><select className="stern-select" name="category" data-testid="stern-club-category" defaultValue={club.category} key={club.category}><option value="">Uncategorized</option>{CLUB_CATEGORIES.map(c => <option key={c} value={c}>{statusLabel(c)}</option>)}</select></Field>
          <Field label="Website"><input className="stern-input" name="website" type="url" data-testid="stern-club-website-edit" defaultValue={club.website} key={club.website}/></Field><Field label="Instagram"><input className="stern-input" name="instagram" data-testid="stern-club-instagram-edit" defaultValue={club.instagram} key={club.instagram}/></Field><Field label="Coffee chat form"><input className="stern-input" name="coffee_chat_form_url" type="url" data-testid="stern-club-chat-form-edit" defaultValue={club.coffee_chat_form_url} key={club.coffee_chat_form_url}/></Field><Field label="Target coffee chats"><input type="number" min={0} max={100} className="stern-input stern-mono" name="target_chats" data-testid="stern-club-chat-target" defaultValue={club.target_chats} key={club.target_chats}/></Field><Field label="Notes"><textarea name="notes" className="stern-textarea" data-testid="stern-club-notes" defaultValue={club.notes} key={club.notes} rows={4}/></Field><RecruitingButton primary type="submit" data-testid="stern-club-save">Save club details</RecruitingButton>
        </fieldset></form></SternSection>
      </div><div className="stern-stack"><SternSection title="E-board people"><People club={club} disabled={disabled} draftsAvailable={draftsAvailable} mutate={mutate} error={state.notice} compact/></SternSection><SternSection title="Recent activity"><Activity rows={club.timeline.slice(0,5)} busy={busy} undo={batch => void state.undo(batch)}/></SternSection></div></div></TabsContent>
      <TabsContent value="people"><SternSection title="E-board people" note="Record status after a conversation or email."><People club={club} disabled={disabled} draftsAvailable={draftsAvailable} mutate={mutate} error={state.notice}/></SternSection></TabsContent>
      <TabsContent value="application"><div className="stern-stack"><DeadlineStrip deadlines={snapshot.deadlines.filter(d => d.clubId === clubId)}/>{!club.programs.length && <EmptyState title="No programs added yet" hint="Add a program to track its application and interview details."/>}<div className="stern-program-grid" data-testid="stern-application-list">{club.programs.map(program => <ProgramCard key={program.id} program={program} editing disabled={disabled} mutate={mutate}/>)}</div><RecruitingButton data-testid="stern-program-add" disabled={disabled} onClick={() => setAddingProgram(true)}><Plus size={14}/>Add program</RecruitingButton></div></TabsContent>
      <TabsContent value="prep"><InterviewPrep club={club} disabled={disabled} mutate={mutate}/></TabsContent>
      <TabsContent value="timeline"><SternSection title="Timeline" note="Club changes and touchpoints with affiliated people, newest first."><Activity rows={club.timeline} busy={busy} undo={batch => void state.undo(batch)}/></SternSection></TabsContent>
    </Tabs>
    <RecruitingDialog error={state.notice} title="Archive this club" open={archiving} onOpenChange={setArchiving}><p>Keep the club's programs, checklist and conversations in Archived.</p><RecruitingButton primary data-testid="stern-club-archive-confirm" disabled={busy} onClick={async () => { if (await mutate({ action: "club.archive", clubId })) setArchiving(false); }}>Archive club</RecruitingButton></RecruitingDialog>
    <RecruitingDialog error={state.notice} title="Add program" open={addingProgram} onOpenChange={setAddingProgram}><form className="stern-form-stack" onSubmit={async e => { e.preventDefault(); if (await mutate({ action: "program.upsert", program: { club_id: clubId, ...Object.fromEntries(new FormData(e.currentTarget)) } })) setAddingProgram(false); }}><Field label="Program name"><input required className="stern-input" name="name" data-testid="stern-new-program-name"/></Field><Field label="Track"><select className="stern-select" name="track" data-testid="stern-new-program-track">{PROGRAM_TRACKS.map(track => <option value={track} key={track}>{statusLabel(track)}</option>)}</select></Field><RecruitingButton primary disabled={busy} type="submit" data-testid="stern-new-program-save">Add program</RecruitingButton></form></RecruitingDialog>
  </SternPage>;
}
